#!/usr/bin/env bash

printf "\e[33;1m%s\e[0m\n" 'Ejecutando Flutter analyzer'
flutter analyze
if [ $? -ne 0 ]; then
  exit 1
fi

printf "\e[33;1m%s\e[0m\n" 'Ejecutando pruebas de unidad...'
flutter test
if [ $? -ne 0 ]; then
  exit 1
fi
