# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  lane :publish_to_internal do
    
    # Compilamos el appbundle
    Dir.chdir "../.." do
      sh("flutter", "pub", "get")
      sh("flutter", "clean")
      sh("flutter", "build", "appbundle") #, "--build-number=#{build_number}"
    end

    # Lo subimos a la Play Store
    upload_to_play_store(track: 'internal',
                         aab: '../build/app/outputs/bundle/release/app-release.aab',
                         release_status: 'draft')
    
  end

end
