name: Actualizar Pods

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      # Solo se ejecutará las actualizaciones cuando cambie el pubspec
      - "pubspec.yaml"

jobs:
  actualizar-pods:
    if: (github.actor == 'dependabot[bot]') && (github.event.pull_request.merged == true)
    name: Actualizar Pods (iOS/Mac)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Realizando actualizacion de pods
        run: |
          cd iOS
          pod update
          pod update Sentry/HybridSDK
          cd ..
          cd macos
          pod update
          pod update Sentry/HybridSDK
