name: Actualizar Pods

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      # Solo se ejecutará las actualizaciones cuando cambie el pubspec
      - "pubspec.lock"
      - "pubspec.yaml"

jobs:
  actualizar-pods:
    if: contains(fromJson('["push", "workflow_dispatch"]'), github.event_name)
    name: Actualizar Pods (iOS/Mac)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Verificamos cambios en el pubspec.
        uses: tj-actions/verify-changed-files@v13
        id: verify-changed-files
        with:
          files: |
            pubspec.lock
            pubspec.yaml

      - id: realizar-validacion
        if: steps.verify-changed-files.outputs.files_changed == 'false'
        run: |
          echo "✖️ No hubo cambios en el pubspec"
          exit 0

      - name: Obtenemos la version de Flutter de pubspec.yaml
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:"
          architecture: x64

      - name: Obtener dependencias de flutter
        run: flutter pub get

      - name: Realizando actualizacion de pods
        run: |
          cd iOS
          pod update
          pod update Sentry/HybridSDK
          cd ..
          cd macos
          pod update
          pod update Sentry/HybridSDK

      - name: Guardando los archivos actualizados.
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add -A 
          git commit -m "Actualizacion de cocoapods para iOS y MacOS"
          git push
