name: Actualizar Pods

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      # Solo se ejecutará las actualizaciones cuando cambie el pubspec
      - "**.lock"
      - "**.yaml"

jobs:
  actualizar-pods:
    if: contains(fromJson('["push", "workflow_dispatch"]'), github.event_name)
    name: Actualizar Pods (iOS/Mac)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Realizando actualizacion de pods
        run: |
          cd iOS
          pod update
          pod update Sentry/HybridSDK
          cd ..
          cd macos
          pod update
          pod update Sentry/HybridSDK
