name: CI

on:
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Obtenemos archivos modificados
        id: archivos-modificados
        uses: tj-actions/changed-files@v35
        with:
          separator: ","
          files: |
            **/*.cpp
            **/*.h

      - name: Si existe algun archivo cpp o .h modificado, asignamos el valor a la variable
        id: verificar_archivos
        if: steps.archivos-modificados.outputs.any_changed == 'true'
        run: |
          echo "librerias_modificadas=true" >> $GITHUB_OUTPUT
          echo "List all the files that have changed: ${{ steps.changed-files-excluded.outputs.all_changed_files }}"