name: Flutter CI

on: push

jobs:
  build-and-release-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.0.2"
      - name: Instalar dependencias del proyecto
        run: flutter pub get
      - name: Compilar binarios
        run: flutter build windows --release
