name: Deploy Android

on:
  push:
    branches:
      - feat/despliegue-continuo

jobs:
  build-and-deploy-android:
    runs-on: ubuntu-latest
    #timeout-minutes: 5

    steps:
      - name: Bajamos el codigo            
        uses: actions/checkout@v3

      - name: Instalamos Java
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Obtenemos la version de Flutter de pubspec.yaml
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v1

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}

      - name: Descargar certificado JKS de Android
        id: android_keystore
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: key.jks
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          
      - name: Creamos el archivo key.propierties para el firmado del binario
        run: |
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" >> android/key.properties

      - name: Instalar Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0.0'

      - name: Hacemos cache de las dependencias de Ruby
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}          
          restore-keys: ${{ runner.os }}-gems-
      
      - name: Instalar Bundle y gems necesarios
        run: |
          gem install bundler:2.3.17
          bundle config path vendor/bundle
          bundle install

      - name: Publicamos a Google Play (Internal)
        env:
          SUPPLY_JSON_KEY_DATA: ${{ secrets.ANDROID_GOOGLE_SERVICE_ACCOUNT_KEY }}
        # Las acciones de "publish_to_internal" de Fastlane se definen en android/Fastfile
        run: |
          bundle exec fastlane publish_to_internal