name: Despliegue automático

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

<<<<<<< HEAD:.github/workflows/deploy.yml
=======
on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

>>>>>>> 6da91b8 (Deploy - Se mejora config de Conveyor (#489)):.github/workflows/deploy.yaml
jobs:
<<<<<<< HEAD:.github/workflows/deploy.yml
  build-desktop:
    uses: ./.github/workflows/build-desktop.yml

  despliegue:
    needs: [build-desktop]
=======
  build:
    uses: ./.github/workflows/build-desktop.yaml
  despliegue:
    needs: [build]
>>>>>>> eb01c87 (fix - Se corrigen errores de sintaxis de yaml. (#491)):.github/workflows/deploy.yaml
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Descargar binario macOS ARM
        uses: actions/download-artifact@v3
        with:
          name: build-macos-aarch64
          path: ./artifacts

      - name: Descargar binario macOS AMD64
        uses: actions/download-artifact@v3
        with:
          name: build-macos-amd64
          path: ./artifacts

      - name: Descargar binario de Windows
        uses: actions/download-artifact@v3
        with:
          name: build-windows-amd64
          # Windows is not in a tarball, so we extract to a separate directory.
          path: ./artifacts/windows

      - name: Mostrar archivos descargados de los artifacts
        run: ls -R

      - name: Ejecutamos Conveyor
        uses: hydraulic-software/conveyor/actions/build@v1
        env:
          NIGHTLYLINK_SECRET: ${{ secrets.NIGHTLYLINK_SECRET }}
        with:
          command: make site --rerun=all
          extra_flags: "--passphrase=${{ secrets.CONVEYOR_PASSPHRASE }}"
          signing_key: ${{ secrets.CONVEYOR_SIGNING_KEY }}
          agree_to_license: 1

      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.UPLOAD_AWS_S3_KEY_ID }}
          aws_secret_access_key: ${{ secrets.UPLOAD_AWS_S3_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.UPLOAD_AWS_S3_BUCKET }}
          source_dir: "output"
          destination_dir: "eleventax" # Directorio destino en el bucket de S3

      - name: Invalidamos el caché de CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION }}
          PATHS: "/eleventax/*"
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.UPLOAD_AWS_S3_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.UPLOAD_AWS_S3_SECRET_ACCESS_KEY}}

      # - name: Release
      #   uses: "marvinpinto/action-automatic-releases@latest"
      #   with:
      #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #     automatic_release_tag: "latest"
      #     prerelease: false
      #     title: "Flutter Demo"
      #     files: output/*
