name: Pruebas Integración

on:
  pull_request:
    branches: [mob-21-12-22]
  workflow_dispatch:

jobs:
  pruebas-android:
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Obtenemos la version de Flutter de pubspec.yaml
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v2

      - name: Instalamos Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}
          cache: true
          architecture: x64

      - name: Instalar dependencias
        run: flutter pub get

      - name: Generar clases de Dart necesarias con secretos embebidos (y ofuscados)
        run: flutter pub run build_runner build --delete-conflicting-outputs
        # Las variables de entorno tienen que estar disponibles en esta etapa
        # que es cuando se genera el env.g.dart con los secrets "hard codeados"
        # y que se usarán despues en las pruebas
        env:
          MIXPANEL_PROJECT_ID: ${{ secrets.MIXPANEL_PROJECT_ID }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          DB_PASSWORD: 12345

      - name: Descargar certificado JKS de Android
        id: android_keystore
        uses: timheuer/base64-to-file@v1.0.4
        with:
          fileName: key.jks
          encodedString: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}

      - name: Creamos el archivo key.propierties para el firmado del binario
        run: |
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" >> android/key.properties

      - name: Compilar binario para pruebas en Testlab
        run: |
          flutter build apk 
          ./gradlew app:assembleAndroidTest
          ./gradlew app:assembleDebug -Ptarget=integration_test/productos_test.dart
        working-directory: android

      - name: "Nos conectamos con la cuenta de GCloud"
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.ANDROID_TESTLAB_SERVICE_ACCOUNT }}"

      - name: "Configurar Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Ejecutando pruebas en TestLab, esto tardará varios minutos..."
        run: |
          gcloud firebase test android run --type instrumentation \
          --app build/app/outputs/apk/debug/app-debug.apk \
          --test build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk\
          --timeout 5m \
          --device model=b2q,version=30,locale=es,orientation=portrait
