name: Cerrar PR inactivos
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-issue-stale: -1
          days-before-issue-close: -1
          stale-issue-label: "inactivo"
          stale-issue-message: "This issue is stale because it has been open for 30 days with no activity."
          close-issue-message: "This issue was closed because it has been inactive for 14 days since being marked as stale."
          stale-pr-label: "inactivo"
          stale-pr-message: "Este pull request se marcó como inactivo ya que han pasado más de 12 horas sin ninguna actividad. Restan 12 horas más para que se cierre automáticamente"
          close-pr-message: "Este pull request fue cerrado ya que estuvo inactivo por más de 12 horas desde que se marcó como inactivo"
          days-before-pr-stale: 0.5
          days-before-pr-close: 0.5
          repo-token: ${{ secrets.GITHUB_TOKEN }}
