name: Testing

on:
  push:
    branches:
     - main
  pull_request:

jobs:
  unit-tests:
    name: Ejecutando pruebas unitarias en ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v3
      
      - name: Obtenemos la version de Flutter de pubspec.yaml
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v1
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64
          flutter-version: ${{ steps.get-flutter-version.outputs.version }}
        

      # Copiamos los DLLs a la carpeta donde se ejecutan las pruebas de unidad      
      - name: Copiamos DLLs de SQLite para que funcionen las pruebas (solo Windows)      
        if: runner.os == 'Windows'
        run: 
          Copy-Item -Path "assets/windows/*" -Destination "${{ env.FLUTTER_ROOT }}\bin\cache\artifacts\engine\windows-x64"

      # - name: Instalar dependencias
      #   run: flutter pub get

      - name: Ejecutando pruebas unitarias
        run: flutter test        